import React from 'react';
//sliderDescription zmienię na sliderShortDescription - to będzie pod sliderem, a w sliderDescription wrzucę teksty, na podstronie wyświuetlam ifnroamcje z tego samego obiektu co SliderTile
const SliderList = [
    {sliderAnchorHref: ("/realization1"),
    sliderImages: [require("../images/Realizations-images/kwidzyn/kwidzyn1.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn2.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn3.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn4.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn5.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn6.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn7.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn8.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn9.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn10.jpg"),
                    require("../images/Realizations-images/kwidzyn/kwidzyn11.jpg")],
    sliderImagesAlts: [ "kwidzyn1",
                        "kwidzyn2",
                        "kwidzyn3",
                        "kwidzyn4",
                        "kwidzyn5",
                        "kwidzyn6",
                        "kwidzyn7",
                        "kwidzyn8",
                        "kwidzyn9",
                        "kwidzyn10",
                        "kwidzyn11",
                        ],               
    sliderDescription: 'Kwidzyn, Pensjonat Willa Miłosna - remont dachu, dachówka Ceramiczna Klasztorna'
    },
    {sliderAnchorHref: "./realization2",
    sliderImages: [require("../images/Realizations-images/chelmno/chelmno1.jpg"),
                    require("../images/Realizations-images/chelmno/chelmno2.jpg"),
                    require("../images/Realizations-images/chelmno/chelmno3.jpg"),
                    require("../images/Realizations-images/chelmno/chelmno4.jpg"),
                    require("../images/Realizations-images/chelmno/chelmno5.jpg"),
                    require("../images/Realizations-images/chelmno/chelmno6.jpg")],
    sliderImagesAlts: [ "chelmno1",
                        "chelmno2",
                        "chelmno3",
                        "chelmno4",
                        "chelmno5",
                        "chelmno6",
                    ],
    sliderDescription: 'Chełmno - Szkoła katolicka - remont, wymiana poszycia dachowego, dach wielopoziomowy, blachodachówka na rąbek stojący'
    },
    {sliderAnchorHref: "./realization3",
    sliderImages: [require("../images/Realizations-images/pruszcz-gdanski/pruszcz1.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz2.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz3.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz4.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz5.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz6.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz7.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz8.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz9.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz10.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz11.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz12.jpg"),
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz13.jpg"), 
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz14.jpg"), 
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz15.jpg"), 
                    require("../images/Realizations-images/pruszcz-gdanski/pruszcz16.jpg")],
    sliderImagesAlts: [ "pruszcz1",
                        "pruszcz2",
                        "pruszcz3",
                        "pruszcz4",
                        "pruszcz5",
                        "pruszcz6",
                        "pruszcz7",
                        "pruszcz8",
                        "pruszcz9",
                        "pruszcz10",
                        "pruszcz11",
                        "pruszcz12",
                        "pruszcz13",
                        "pruszcz14",
                        "pruszcz15",
                        "pruszcz16",
                ],
    sliderDescription: 'Pruszcz Gdański - Komenda Powiatowa Policji - budowa więźby dachowej, dachówka ceramiczna karpiówka'
    },      
    {sliderAnchorHref: "./realization4",
    sliderImages: [require("../images/Realizations-images/sztutowo/sztutowo1.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo2.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo3.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo4.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo5.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo6.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo7.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo8.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo9.jpg"),
                    require("../images/Realizations-images/sztutowo/sztutowo10.jpg")],
    sliderImagesAlts: [ "sztutowo1",
                        "sztutowo2",
                        "sztutowo3",
                        "sztutowo4",
                        "sztutowo5",
                        "sztutowo6",
                        "sztutowo7",
                        "sztutowo8",
                        "sztutowo9",
                        "sztutowo10",
                    ],                  
    sliderDescription: 'Sztutowo - Polomarket - budowa więźby dachowej, dachówka ceramiczna, podbitka drewniana'
    }
]
 
export default SliderList;